name: Preview Application

on:
    pull_request:
    workflow_dispatch:
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  preview:
    runs-on: ubuntu-latest
    environment:
        name: preview
        url: ${{ steps.deploy.outputs.url }}
    steps:
        - name: Cloning Repository
          uses: actions/checkout@v3

        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Install Dependencies
          run: npm ci --production

        - name: Install Vercel
          run: npm install vercel

        - name: Setup Env in Vercel
          run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

        - name: Build Application
          run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

        - name: Deploy Application
          id: deploy
          run: echo "::set-output name=url::$(yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
